# Generated by Django 5.0.4 on 2024-05-04 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp2", "0002_author_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
